package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0F6D62)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA8F2E2)
val md_theme_light_onPrimaryContainer = Color(0xFF00201C)
val md_theme_light_secondary = Color(0xFF3C6471)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC0E9F7)
val md_theme_light_onSecondaryContainer = Color(0xFF001F27)
val md_theme_light_tertiary = Color(0xFF8A531C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDBB)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6F3EC)
val md_theme_light_onBackground = Color(0xFF161D1B)
val md_theme_light_surface = Color(0xFFFFFBF5)
val md_theme_light_onSurface = Color(0xFF161D1B)
val md_theme_light_surfaceVariant = Color(0xFFD7E5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF3C4944)

val md_theme_dark_primary = Color(0xFF89D6C5)
val md_theme_dark_onPrimary = Color(0xFF003731)
val md_theme_dark_primaryContainer = Color(0xFF005048)
val md_theme_dark_onPrimaryContainer = Color(0xFFA8F2E2)
val md_theme_dark_secondary = Color(0xFFA4CDDB)
val md_theme_dark_onSecondary = Color(0xFF063542)
val md_theme_dark_secondaryContainer = Color(0xFF244C59)
val md_theme_dark_onSecondaryContainer = Color(0xFFC0E9F7)
val md_theme_dark_tertiary = Color(0xFFFFB873)
val md_theme_dark_onTertiary = Color(0xFF4E2600)
val md_theme_dark_tertiaryContainer = Color(0xFF6B3C06)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDBB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0E1513)
val md_theme_dark_onBackground = Color(0xFFDDE5E1)
val md_theme_dark_surface = Color(0xFF111917)
val md_theme_dark_onSurface = Color(0xFFDDE5E1)
val md_theme_dark_surfaceVariant = Color(0xFF3C4944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBCC9C3)
